-- MySQL Script generated by MySQL Workbench
-- Thu May  9 22:15:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testbuddy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testbuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testbuddy` DEFAULT CHARACTER SET utf8 ;
USE `testbuddy` ;

-- -----------------------------------------------------
-- Table `testbuddy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `repo_url` VARCHAR(256) NULL,
  `language_processor` VARCHAR(45) NOT NULL,
  `ci_communicator` VARCHAR(45) NOT NULL,
  `ci_params` TEXT NULL,
  `issue_tracker` VARCHAR(256) NULL,
  `issue_tracker_params` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`trigger_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`trigger_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`result_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`result_state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`ci_run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`ci_run` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` TEXT NULL,
  `trigger_type_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `result_state_id` INT NOT NULL,
  `run_by_user` VARCHAR(256) NULL,
  `pipeline_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pipeline_trigger_type1_idx` (`trigger_type_id` ASC),
  INDEX `fk_ci_run_project1_idx` (`project_id` ASC),
  INDEX `fk_ci_run_result_states1_idx` (`result_state_id` ASC),
  CONSTRAINT `fk_pipeline_trigger_type1`
    FOREIGN KEY (`trigger_type_id`)
    REFERENCES `testbuddy`.`trigger_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ci_run_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `testbuddy`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ci_run_result_states1`
    FOREIGN KEY (`result_state_id`)
    REFERENCES `testbuddy`.`result_state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`test_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`test_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(512) NULL,
  `project_id` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_test_plan_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_test_plan_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `testbuddy`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`test_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`test_module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `test_plan_id` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `name_no_spaces` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_test_modules_test_plan1_idx` (`test_plan_id` ASC),
  CONSTRAINT `fk_test_modules_test_plan1`
    FOREIGN KEY (`test_plan_id`)
    REFERENCES `testbuddy`.`test_plan` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`priority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`test_case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`test_case` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `test_module_id` INT NOT NULL,
  `priority_id` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(256) NULL,
  `scenario_name` VARCHAR(256) NULL,
  `scenario_content` VARCHAR(8196) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_test_case_test_modules1_idx` (`test_module_id` ASC),
  INDEX `fk_test_case_priority1_idx` (`priority_id` ASC),
  CONSTRAINT `fk_test_case_test_modules1`
    FOREIGN KEY (`test_module_id`)
    REFERENCES `testbuddy`.`test_module` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_case_priority1`
    FOREIGN KEY (`priority_id`)
    REFERENCES `testbuddy`.`priority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`test_step_definition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`test_step_definition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(256) NOT NULL,
  `project_id` INT NOT NULL,
  `param_count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_test_step_definition_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_test_step_definition_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `testbuddy`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`test_step`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`test_step` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(256) NULL,
  `test_case_id` INT NOT NULL,
  `order` INT NOT NULL,
  `test_step_definition_id` INT NOT NULL,
  `parameters` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_test_step_test_case1_idx` (`test_case_id` ASC),
  INDEX `fk_test_step_test_step_definition1_idx` (`test_step_definition_id` ASC),
  CONSTRAINT `fk_test_step_test_case1`
    FOREIGN KEY (`test_case_id`)
    REFERENCES `testbuddy`.`test_case` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_step_test_step_definition1`
    FOREIGN KEY (`test_step_definition_id`)
    REFERENCES `testbuddy`.`test_step_definition` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`bug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`bug` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(256) NULL,
  `status` VARCHAR(128) NULL,
  `data` TEXT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bug_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_bug_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `testbuddy`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`gherkin_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`gherkin_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `dir` VARCHAR(256) NULL,
  `fullpath` VARCHAR(256) NULL,
  `parsed_info` TEXT NULL,
  `content_raw` TEXT NOT NULL,
  `ci_run_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_report_ci_run1_idx` (`ci_run_id` ASC),
  CONSTRAINT `fk_report_ci_run1`
    FOREIGN KEY (`ci_run_id`)
    REFERENCES `testbuddy`.`ci_run` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`requirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`requirement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(128) NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_requirements_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_requirements_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `testbuddy`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`user_has_test_case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`user_has_test_case` (
  `test_case_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `fk_test_case_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_test_case_has_user_test_case1_idx` (`test_case_id` ASC),
  CONSTRAINT `fk_test_case_has_user_test_case1`
    FOREIGN KEY (`test_case_id`)
    REFERENCES `testbuddy`.`test_case` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_case_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `testbuddy`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`requirement_has_test_case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`requirement_has_test_case` (
  `requirement_id` INT NOT NULL,
  `test_case_id` INT NOT NULL,
  INDEX `fk_requirements_has_test_case_test_case1_idx` (`test_case_id` ASC),
  INDEX `fk_requirements_has_test_case_requirements1_idx` (`requirement_id` ASC),
  CONSTRAINT `fk_requirements_has_test_case_requirements1`
    FOREIGN KEY (`requirement_id`)
    REFERENCES `testbuddy`.`requirement` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requirements_has_test_case_test_case1`
    FOREIGN KEY (`test_case_id`)
    REFERENCES `testbuddy`.`test_case` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`test_step_definition_has_gherkin_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`test_step_definition_has_gherkin_type` (
  `test_step_definition_id` INT NOT NULL AUTO_INCREMENT,
  `gherkin_type_id` INT NOT NULL,
  INDEX `fk_test_step_definition_has_gherkin_type_gherkin_type1_idx` (`gherkin_type_id` ASC),
  INDEX `fk_test_step_definition_has_gherkin_type_test_step_definiti_idx` (`test_step_definition_id` ASC),
  CONSTRAINT `fk_test_step_definition_has_gherkin_type_test_step_definition1`
    FOREIGN KEY (`test_step_definition_id`)
    REFERENCES `testbuddy`.`test_step_definition` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_step_definition_has_gherkin_type_gherkin_type1`
    FOREIGN KEY (`gherkin_type_id`)
    REFERENCES `testbuddy`.`gherkin_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`ci_run_has_bug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`ci_run_has_bug` (
  `ci_run_id` INT NOT NULL AUTO_INCREMENT,
  `bug_id` INT NOT NULL,
  INDEX `fk_ci_run_has_bug_bug1_idx` (`bug_id` ASC),
  INDEX `fk_ci_run_has_bug_ci_run1_idx` (`ci_run_id` ASC),
  CONSTRAINT `fk_ci_run_has_bug_ci_run1`
    FOREIGN KEY (`ci_run_id`)
    REFERENCES `testbuddy`.`ci_run` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ci_run_has_bug_bug1`
    FOREIGN KEY (`bug_id`)
    REFERENCES `testbuddy`.`bug` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`ci_run_has_test_case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`ci_run_has_test_case` (
  `ci_run_id` INT NOT NULL AUTO_INCREMENT,
  `test_case_id` INT NOT NULL,
  INDEX `fk_ci_run_has_test_case_test_case1_idx` (`test_case_id` ASC),
  INDEX `fk_ci_run_has_test_case_ci_run1_idx` (`ci_run_id` ASC),
  CONSTRAINT `fk_ci_run_has_test_case_ci_run1`
    FOREIGN KEY (`ci_run_id`)
    REFERENCES `testbuddy`.`ci_run` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ci_run_has_test_case_test_case1`
    FOREIGN KEY (`test_case_id`)
    REFERENCES `testbuddy`.`test_case` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`user_has_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC),
  INDEX `fk_user_has_role_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `testbuddy`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `testbuddy`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(256) NOT NULL,
  `category` VARCHAR(256) NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_tag_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `testbuddy`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`requirement_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`requirement_has_tag` (
  `requirement_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  INDEX `fk_requirement_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_requirement_has_tag_requirement1_idx` (`requirement_id` ASC),
  CONSTRAINT `fk_requirement_has_tag_requirement1`
    FOREIGN KEY (`requirement_id`)
    REFERENCES `testbuddy`.`requirement` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requirement_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `testbuddy`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbuddy`.`user_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbuddy`.`user_has_project` (
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  INDEX `fk_user_has_project_project1_idx` (`project_id` ASC),
  INDEX `fk_user_has_project_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_project_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `testbuddy`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `testbuddy`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
