# generated by sqlacodegen, available from: "https://pypi.org/project/sqlacodegen/":
# 1. go to your docker container shell: e.g. docker exec -it backend /bin/bash
# 2. run: e.g sqlacodegen mysql://root:admin@dbs:1234/testbuddy
import json

from flask import jsonify
from sqlalchemy import Column, Date, DateTime, ForeignKey, String, Table, Text
from sqlalchemy.dialects.mysql import INTEGER, VARCHAR
from sqlalchemy.orm import relationship
from app import dbs

Base = dbs.Model
metadata = Base.metadata


class Bug(Base):
    __tablename__ = "bug"

    id = Column(INTEGER(11), primary_key=True)
    link = Column(String(256))
    status = Column(String(128))
    ci_runs = relationship('CIRun', secondary='ci_run_has_bug', back_populates="bugs")
    data = Column(Text)  # relevant information e.g. test case with a bug etc

    project_id = Column(ForeignKey("project.id", ondelete="CASCADE"), nullable=False, index=True)
    project = relationship("Project", back_populates="bugs")

    def get_data(self):
        try:
            return json.loads(self.data)
        except Exception as e:
            return {}

    def set_data(self, new_data):
        self.data = json.dumps(new_data)

    def to_dict(self, recursion_limit=1):
        ci_runs = []
        if recursion_limit > 0:
            for c_r in self.ci_runs:
                ci_runs.append(c_r.to_dict(recursion_limit - 1))
        else:
            ci_runs = [{"id": ci_r.id, "pipeline_id": ci_r.pipeline_id} for ci_r in self.ci_runs]
        ret_data = {}
        ret_data = {"id": self.id, "link": self.link, "status": self.status, "data": self.get_data()}
        if ci_runs:
            ret_data["ci_runs_affected"] = ci_runs
        return ret_data

    def to_json(self):
        return jsonify(self.to_dict())


class GherkinType(Base):
    __tablename__ = "gherkin_type"

    id = Column(INTEGER(11), primary_key=True)
    name = Column(String(45), nullable=False)

    test_step_definitions = relationship("TestStepDefinition", secondary="test_step_definition_has_gherkin_type",
                                         back_populates="gherkin_types")

    def to_dict(self):
        return {"id": self.id, "name": self.name}

    def to_json(self):
        return jsonify(self.to_dict())


class Priority(Base):
    __tablename__ = "priority"

    id = Column(INTEGER(11), primary_key=True)
    type = Column(String(45), nullable=False)

    def to_dict(self):
        return {"id": self.id, "type": self.type}

    def to_json(self):
        return jsonify(self.to_dict())


class Project(Base):
    __tablename__ = "project"

    id = Column(INTEGER(11), primary_key=True)
    name = Column(String(45), nullable=False)
    repo_url = Column(String(256))
    language_processor = Column(String(45), nullable=False)
    ci_communicator = Column(String(45), nullable=False)
    issue_tracker = Column(String(256))
    issue_tracker_params = Column(Text)
    ci_params = Column(Text)  # {"server":"", "key":""}

    ci_runs = relationship("CIRun", back_populates="project", cascade="all,delete", passive_deletes=True)
    users = relationship("User", secondary="user_assigned_project", back_populates="projects")
    test_plan = relationship("TestPlan", uselist=False, passive_deletes=True,
                             cascade="all,delete", back_populates="project")
    requirements = relationship("Requirement", passive_deletes=True, cascade="all,delete", back_populates="project")
    test_step_definitions = relationship("TestStepDefinition", back_populates="project")
    bugs = relationship("Bug", back_populates="project")
    tags = relationship("Tag", back_populates="project")

    def get_ci_params(self):
        try:
            return json.loads(self.ci_params)
        except Exception as e:
            return {}

    def set_ci_params(self, new_params):
        self.ci_params = json.dumps(new_params)

    def get_issue_tracker_params(self):
        try:
            return json.loads(self.issue_tracker_params)
        except Exception as e:
            return {}

    def set_issue_tracker_params(self, new_params):
        self.issue_tracker_params = json.dumps(new_params)


    def to_dict(self):
        if self.test_plan is None:
            tp = None
        else:
            tp = {"id": str(self.test_plan.id), "name": self.test_plan.name}
        return {"id": self.id, "name": self.name, "repo_url": self.repo_url, "ci_params": self.get_ci_params(),
                "ci_communicator": self.ci_communicator, "processor": self.language_processor,
                "testplan": tp,
                "issue_tracker_params": self.get_issue_tracker_params()}

    def to_json(self):
        return jsonify(self.to_dict())


class Report(Base):
    __tablename__ = "report"

    id = Column(INTEGER(11), primary_key=True)
    ci_run_id = Column(ForeignKey("ci_run.id", ondelete="CASCADE"), nullable=False, index=True)
    date = Column(DateTime)
    dir = Column(String(256))
    fullpath = Column(String(256))
    content_raw = Column(Text, nullable=False)
    parsed_info = Column(Text)
    ci_run = relationship("CIRun", uselist=False, back_populates="report")

    def get_parsed_info(self):
        try:
            return json.loads(self.parsed_info)
        except Exception as e:
            return {}

    def set_parsed_info(self, new_data):
        self.parsed_info = json.dumps(new_data)

    def to_dict(self):
        ci_run = {"id": self.ci_run.id, "pipeline_id": self.ci_run.pipeline_id,
                  "overall_result: ": self.ci_run.result_state.name}
        return {"id": self.id, "ci_run": ci_run, "report_data": self.get_parsed_info()}

    def to_json(self):
        return jsonify(self.to_dict())


class ResultState(Base):
    __tablename__ = "result_state"

    id = Column(INTEGER(11), primary_key=True)
    name = Column(String(45))

    def to_dict(self):
        return {"id": self.id, "type": self.type}

    def to_json(self):
        return jsonify(self.to_dict())


class Role(Base):
    __tablename__ = "role"

    id = Column(INTEGER(11), primary_key=True)
    name = Column(String(45))
    users = relationship("User", secondary="user_has_role", back_populates="roles")

    def to_dict(self):
        return {"id": self.id, "name": self.name}

    def to_json(self):
        return jsonify(self.to_dict())


class TriggerType(Base):
    __tablename__ = "trigger_type"

    id = Column(INTEGER(11), primary_key=True)
    type = Column(INTEGER(128), nullable=False)
    ci_runs = relationship("CIRun", back_populates="trigger_type")

    def to_dict(self):
        ci_runs = []
        for ci_run in self.ci_runs:
            ci_runs.append(ci_run.to_dict())
        return {"id": self.id, "type": self.type, "ci_run": ci_runs}

    def to_json(self):
        return jsonify(self.to_dict())


class CIRun(Base):
    __tablename__ = "ci_run"

    id = Column(INTEGER(11), primary_key=True)
    data = Column(Text)
    trigger_type_id = Column(ForeignKey("trigger_type.id"), nullable=False, index=True)
    project_id = Column(ForeignKey("project.id", ondelete="CASCADE"), nullable=False, index=True)
    result_state_id = Column(ForeignKey('result_state.id'), nullable=False, index=True)
    run_by_user = Column(String(256))
    pipeline_id = Column(INTEGER(11), nullable=False)

    result_state = relationship("ResultState", uselist=False)
    project = relationship("Project", uselist=False, back_populates="ci_runs")
    trigger_type = relationship("TriggerType", uselist=False, back_populates="ci_runs")
    report = relationship("Report", back_populates="ci_run", uselist=False)
    test_cases = relationship('TestCase', secondary='ci_run_has_test_case', back_populates="ci_runs",
                              cascade="all,delete", passive_deletes=True)
    bugs = relationship("Bug", secondary="ci_run_has_bug", back_populates="ci_runs")

    def get_data(self):
        try:
            return json.loads(self.data)
        except Exception as e:
            return {}

    def set_data(self, new_data):
        self.data = json.dumps(new_data)

    def to_dict(self, recursion_limit=1):
        bugs = []
        if recursion_limit > 0:
            for b in self.bugs:
                bugs.append(b.to_dict(recursion_limit-1))
        else:
            bugs = [b.id for b in self.bugs]
        return {"id": self.id, "pipeline_id": self.pipeline_id, "data": self.get_data(),
                "trigger_type": self.trigger_type.type, "bugs": bugs}

    def to_json(self):
        return jsonify(self.to_dict())


t_ci_run_has_test_case = Table(
    'ci_run_has_test_case', metadata,
    Column('ci_run_id', ForeignKey('ci_run.id'), nullable=False, index=True),
    Column('test_case_id', ForeignKey('test_case.id'), nullable=False, index=True)
)


t_ci_run_has_bug = Table(
    'ci_run_has_bug', metadata,
    Column('ci_run_id', ForeignKey('ci_run.id'), nullable=False, index=True),
    Column('bug_id', ForeignKey('bug.id'), nullable=False, index=True)
)


class Tag(Base):
    __tablename__ = "tag"

    id = Column(INTEGER(11), primary_key=True)
    content = Column(String(256))
    category = Column(String(256))
    requirements = relationship('Requirement', secondary='requirement_has_tag', back_populates="tags")

    project_id = Column(ForeignKey("project.id", ondelete="CASCADE"), nullable=False, index=True)
    project = relationship("Project", back_populates="tags")

    def to_dict(self):
        return {"id": self.id, "content": self.content, "category": self.category, "project_id": self.project_id}

    def to_json(self):
        return jsonify(self.to_dict())


class TestPlan(Base):
    __tablename__ = "test_plan"

    id = Column(INTEGER(11), primary_key=True)
    description = Column(String(512))
    name = Column(String(128))
    project_id = Column(ForeignKey("project.id", ondelete="CASCADE"), nullable=False, index=True)

    project = relationship("Project", uselist=False, back_populates="test_plan")
    test_modules = relationship("TestModule", back_populates="test_plan", cascade="all,delete", passive_deletes=True)

    def to_dict(self):
        tmods = []
        for tm in self.test_modules:
            tmods.append(tm.to_dict())
        return {"id": self.id, "description": self.description, "name": self.name,
                "project": {"project_name": self.project.name, "project_id": self.project.id},
                "test_modules": tmods}

    def to_json(self):
        return jsonify(self.to_dict())


class TestStepDefinition(Base):
    __tablename__ = "test_step_definition"

    id = Column(INTEGER(11), primary_key=True)
    content = Column(String(256), nullable=False)
    param_count = Column(INTEGER(11), nullable=False)
    project_id = Column(ForeignKey("project.id", ondelete="CASCADE"), nullable=False, index=True)

    gherkin_types = relationship('GherkinType', secondary='test_step_definition_has_gherkin_type',
                                 back_populates="test_step_definitions", cascade="all,delete", passive_deletes=True)
    test_steps = relationship('TestStep', back_populates='test_step_definition')
    project = relationship("Project", uselist=False, back_populates="test_step_definitions")

    def to_dict(self):
        return {"id": self.id, "gherkin_type": self.gherkin_types[0].name,
                "project": {"project_name": self.project.name, "project_id": self.project.id},
                "content": self.content, "param_count": self.param_count}

    def to_json(self):
        return jsonify(self.to_dict())


class User(Base):
    __tablename__ = "user"

    id = Column(INTEGER(11), primary_key=True)
    username = Column(String(64), unique=True, nullable=False)
    password_hash = Column(String(45), nullable=False)
    name = Column(String(45))
    surname = Column(String(45))

    roles = relationship("Role", secondary="user_has_role", back_populates="users")
    projects = relationship("Project", secondary="user_assigned_project", back_populates="users")
    assigned_test_cases = relationship("TestCase", secondary="user_has_test_case",
                                       back_populates="users_assigned", cascade="all,delete", passive_deletes=True)

    def to_dict(self):
        u_roles = []
        for r in self.roles:
            u_roles.append(r.to_dict())
        return {"id": self.id, "username": self.username, "name": self.name, "surname": self.surname, "roles": u_roles}

    def to_json(self):
        return jsonify(self.to_dict())


t_user_has_role = Table(
    'user_has_role', metadata,
    Column('user_id', ForeignKey('user.id'), nullable=False, index=True),
    Column('role_id', ForeignKey('role.id'), nullable=False, index=True)
)

t_test_step_definition_has_gherkin_type = Table(
    "test_step_definition_has_gherkin_type", metadata,
    Column("gherkin_type_id", ForeignKey("gherkin_type.id"), nullable=False, index=True),
    Column("test_step_definition_id", ForeignKey("test_step_definition.id"), nullable=False, index=True)
)


class TestModule(Base):
    __tablename__ = "test_module"

    id = Column(INTEGER(11), primary_key=True)
    test_plan_id = Column(ForeignKey("test_plan.id", ondelete="CASCADE"), nullable=False, index=True)
    name = Column(String(128), nullable=False)
    name_no_spaces = Column(String(128), nullable=False)

    test_cases = relationship("TestCase", back_populates="test_module", cascade="all,delete", passive_deletes=True)
    test_plan = relationship("TestPlan", back_populates="test_modules")

    def to_dict(self):
        tcases = []
        for tc in self.test_cases:
            tcases.append(tc.to_dict())
        return {"id": self.id, "name": self.name, "testcases": tcases, "name_no_spaces": self.name_no_spaces}

    def to_json(self):
        return jsonify(self.to_dict())


t_user_assigned_project = Table(
    "user_assigned_project", metadata,
    Column("user_id", ForeignKey("user.id"), nullable=False, index=True),
    Column("project_id", ForeignKey("project.id"), nullable=False, index=True)
)


class Requirement(Base):
    __tablename__ = "requirement"

    id = Column(INTEGER(11), primary_key=True)
    content = Column(String(128))
    project_id = Column(ForeignKey("project.id", ondelete="CASCADE"), nullable=False, index=True)

    project = relationship("Project", uselist=False, back_populates="requirements")
    tags = relationship("Tag", back_populates="requirements", secondary='requirement_has_tag',
                        cascade="all,delete", passive_deletes=True)
    test_cases = relationship("TestCase", secondary="requirement_has_test_case", back_populates='requirements',
                              cascade="all,delete", passive_deletes=True)

    def to_dict(self, recursion_limit=1):
        tcases = []
        if recursion_limit > 0:
            for tc in self.test_cases:
                tcases.append(tc.to_dict())
        else:
            tcases = [tc.id for tc in self.test_cases]
        tags = []
        for t in self.tags:
            tags.append(t.to_dict())
        return {"id": self.id, "project": {"project_name": self.project.name, "project_id": self.project.id},
                "content": self.content, "tags": tags, "in_test_cases": tcases}

    def to_json(self):
        return jsonify(self.to_dict())


class TestCase(Base):
    __tablename__ = "test_case"

    id = Column(INTEGER(11), primary_key=True)
    test_module_id = Column(ForeignKey("test_module.id", ondelete="CASCADE"), nullable=False, index=True)
    priority_id = Column(ForeignKey("priority.id"), nullable=False, index=True)
    name = Column(String(128), nullable=False)
    description = Column(String(256))
    scenario_name = Column(String(256))
    scenario_content = Column(String(8196))

    priority = relationship("Priority", uselist=False)
    test_module = relationship("TestModule", uselist=False, back_populates="test_cases")
    users_assigned = relationship("User", secondary="user_has_test_case", back_populates="assigned_test_cases",
                                  cascade="all,delete", passive_deletes=True)
    test_steps = relationship("TestStep", back_populates="test_case", cascade="all,delete", passive_deletes=True)
    ci_runs = relationship('CIRun', secondary='ci_run_has_test_case', back_populates="test_cases",
                           cascade="all,delete", passive_deletes=True)
    requirements = relationship('Requirement', secondary="requirement_has_test_case", back_populates='test_cases',
                                cascade="all,delete", passive_deletes=True)

    def to_dict(self):
        tsteps = []
        for step in self.test_steps:
            tsteps.append(step.to_dict())
        return {"id": self.id, "name": self.name, "priority": self.priority.type, "scenario_name": self.scenario_name,
                "steps": tsteps}  # , "story_file_content": self.story_file_content }

    def to_json(self):
        return jsonify(self.to_dict())


t_requirements_has_test_case = Table(
    "requirement_has_test_case", metadata,
    Column("requirement_id", ForeignKey("requirement.id"), nullable=False, index=True),
    Column("test_case_id", ForeignKey("test_case.id"), nullable=False, index=True)
)

t_requirements_has_tag = Table(
    "requirement_has_tag", metadata,
    Column("requirement_id", ForeignKey("requirement.id"), nullable=False, index=True),
    Column("tag_id", ForeignKey("tag.id"), nullable=False, index=True)
)


class TestStep(Base):
    __tablename__ = "test_step"

    id = Column(INTEGER(11), primary_key=True)
    content = Column(String(256))
    test_case_id = Column(ForeignKey("test_case.id", ondelete="CASCADE"), nullable=False, index=True)
    test_step_definition_id = Column(ForeignKey("test_step_definition.id", ondelete="CASCADE"), nullable=False,
                                     index=True)
    parameters = Column(String(1024))
    order = Column(INTEGER(), nullable=False)

    test_case = relationship("TestCase", back_populates="test_steps", uselist=False)
    test_step_definition = relationship("TestStepDefinition", uselist=False, back_populates="test_steps")

    def get_params(self):
        try:
            return json.loads(self.parameters)
        except Exception as e:
            return {}

    def set_params(self, new_params):
        self.parameters = json.dumps(new_params)


    def to_dict(self):
        return {"id": self.id, "content": self.content, "order": self.order,
                "definition": self.test_step_definition.to_dict()}

    def to_json(self):
        return jsonify(self.to_dict())


t_user_has_test_case = Table(
    "user_has_test_case", metadata,
    Column("test_case_id", ForeignKey("test_case.id", ondelete="CASCADE"), nullable=False, index=True),
    Column("user_id", ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True)
)

dbs.create_all()
